allowBuilds:
  better-sqlite3: true
  esbuild: true
  protobufjs: false
minimumReleaseAgeExclude:
  - ras-stack@0.30.0
minimumReleaseAge: 10080
peerDependencyRules:
  allowedVersions:
    better-sqlite3: '13'
